POST http://localhost:3000/order
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "modelId": "0003a782-14d9-4d3f-839e-3db7f7c7f25c",
    "transmission": "AUTO",
    "bodyType": "SEDAN",
    "drive": "FULL",
    "year": "2021",
    "engineVolume": "3.3",
    "vin": "sdgsdfgsdfgsd",
    "carPart": "кардан",
    "fuel": ["GASOLINE", "ELECTRO", "HYBRID"],
    "part": "ORIGINAL"
}

###
GET http://localhost:3000/transport
Content-Type: application/json

###
GET http://localhost:3000/transport/brands/auto
Content-Type: application/json

###
GET http://localhost:3000/transport/models/3db4c476-a81a-4da2-9262-dfd47479ef66/75726b82-aa27-42c9-a83b-fedd74228812
Content-Type: application/json

###

@accessToken = {{login.response.body.access_token}}

POST http://localhost:3000/user/register
content-type: application/json

{
  "firstName": "user",
  "lastName": "Last Name",
  "email": "user@gmail222.com",
  "phoneNumber": "123123"
}

###

# @name login
POST http://localhost:3000/auth/login
content-type: application/json

{
  "phoneNumber": "123123"
}

###

GET http://localhost:3000/user/self
Authorization: Bearer {{accessToken}}
###

POST http://localhost:3000/user/is-exist
content-type: application/json
Authorization: Bearer {{accessToken}}

{
  "email": "ron@gmail.com"
}
