@accessToken = {{login.response.body.access_token}}
POST http://localhost:3000/order
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "modelId": "0003a782-14d9-4d3f-839e-3db7f7c7f25c",
    "transmission": "AUTO",
    "bodyType": "SEDAN",
    "drive": "FULL",
    "year": "2021",
    "engineVolume": "3.3",
    "vin": "sdgsdfgsdfgsd",
    "carPart": "кардан",
    "fuel": ["GASOLINE", "ELECTRO", "HYBRID"],
    "part": "ORIGINAL"
}

###
GET http://localhost:3000/transport
Content-Type: application/json

###
GET http://localhost:3000/transport/brands/moto
Content-Type: application/json

###
GET http://localhost:3000/transport/models/1f52a3dd-1950-4c34-910c-93f735bd95b2/b002fc00-cd72-47a7-ac70-29550bb2c2af
Content-Type: application/json

###


POST http://192.168.88.35:3000/user/register
content-type: application/json

{
  "firstName": "user221",
  "lastName": "Last 221",
  "email": "user221@gmail222.com",
  "phoneNumber": "221",
  "telegramNotification": true
}

###

# @name login
POST http://192.168.88.35:3000/auth/login
content-type: application/json

{
  "phoneNumber": "221"
}

###

GET http://localhost:3000/user/self
Authorization: Bearer {{accessToken}}
###

POST http://localhost:3000/user/is-exist
content-type: application/json
Authorization: Bearer {{accessToken}}

{
  "email": "ron@gmail.com"
}

###
POST http://localhost:3000/transport/brand
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Samsung",
  "type": "moto"
}

###
POST http://localhost:3000/transport/model
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "A51",
  "brand": "Samsung",
  "type": "moto"
}