version: '3.5'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-auto_opt}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1}
      POSTGRES_DB: ${POSTGRES_DB:-auto_db}
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
