version: '3.5'

services:
  api:
    container_name: auto_opt_api
    build:
      context: ./
      target: production
    ports:
      - 3000:3000
    command: 
      - node 
      - dist/src/main
    env_file:
      - ./.env
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-auto_opt}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1}
      POSTGRES_DB: ${POSTGRES_DB:-auto_db}
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - "5432:5432"
    restart: always

volumes:
    postgres:
